### ISSUE TITLE
AMAZING!

### ISSUE THREAD

**Issue by hamin** [goloveychuk/SwiftPQ#2]
Sorry didn't know where else to say this but I'd been working on a Purse swift postgres driver since early/mid 2016. Going through Swift 2 > 3 migration was painful and mostly procrastinated working on it. But it seems liek you've made more progress (paraemetrized queries and auth) then I did and I'd like to combine the efforts and contribute anyway I can :).

Here were my efforts: https://github.com/hamin/swift-pg 

Not as clean as complete as yours :) . But i'd love to combine forces and move this forward. For one I'd like to extract the socket part so other libs can bring there own socket lib provided they conform to protocol that works with SwiftPQ. If you're interested in talking further let me know :). Feel free to close this issue. Again...thanks for your contributions. This is aweseome!

**Comment by goloveychuk** [comment]
Thanks :)
You can easily make PRs. It would be great.
Regarding socket protocols - already have this
https://github.com/goloveychuk/SwiftPQ/blob/master/Sources/Socket.swift
just don't have socket option in connection constructor. It's several minutes fix. 
what is done good - types. 
e.g. https://github.com/goloveychuk/SwiftPQ/blob/master/Sources/Types.swift#L316
Not all, but major are done. Still have an idea to support postgres structs, and deserializing it to swift structs. 
maybe https://github.com/Zewo/Reflection needed.

tests for all supported types. https://github.com/goloveychuk/SwiftPQ/blob/master/Tests/PurePostgresTests/PurePostgresTests.swift#L50

Also, I'm pretty sure I have several bugs in protocol implementation. Looks like it's works ok, but I guess there are cases, where it go to inconsistent state, and I don't catch it. Like reconnection, errors, exceptions and other.
Also, lib should be tested for concurrency.
